### ISSUE TITLE
JSON Parse Error

### ISSUE THREAD

**Issue by chanchancel** [mboya/mpesa_stk#73]
I see you guys wanted a description of errors, right?
After installing all the requirements: redis & .env. Am getting some errors.
On the action view side:

an error is raised at:
`MpesaStk::Push.pay_bill("500", "2547xxxxxxxx")`
apparently a json parse error
with the message:  784: unexpected token at '' 

I tried the irb test all it gives is:
{"requestId"=>"21242-9965227-1", "errorCode"=>"404.001.03", "errorMessage"=>"Invalid Access Token"}

I suspect the issue is internal, since the code is literally a one liner.
Thanks

**Comment by chanchancel** [comment]
my bad on further investigation.
Safaricom servers are the ones issuing 5xx error. 
The error is originating from Safaricom itself and not you guys.

**Comment by cesswairimu** [comment]
Gotcha, thanks
